im:
  tcpPort: 9001
  webSocketPort: 19001
  bossThreadSize: 1
  workerThreadSize: 8
  heartBeatTime: 3000 #心跳超时时间，ms
  brokerId: 1001
  loginModel: 1
  # 1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
  # 2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
  # 3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
  # 4 允许所有端多设备登录 不踢任何设备

  redis:
    mode: single # 单机模式
    database: 0
#    password: 123456
    timeout: 3000 # 超时时间
    poolMinIdle: 8 # 最小空闲数
    poolConnTimeout: 3000 # 连接超时时间
    poolSize: 10 # 连接池大小
    single:
      address: 192.168.199.100:6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: guest
    password: guest

  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000