# 端口
server:
  port: 8000


spring:
  profiles:
    # 开发环境
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im-core?serverTimezone=UTC
    username: root
    password: 123456

  redis:
    host: 192.168.199.100
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10

  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost
    username: guest
    password: guest
    virtual-host:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0
    publisher-confirm-type: correlated
  application:
    name: im-core
  main:
    allow-circular-references: true

appConfig:
  privateKey: 123456
  zkAddr: 127.0.0.1:2181
  zkConnectTimeOut: 5000
  imRouteWay: 3   # 1：随机   2：轮询   3：一致性哈希
  consistentHashWay: 1
  sendMessageCheckFriend: true # 发送消息是否校验关系链
  sendMessageCheckBlack: true # 发送消息是否校验黑名单
  ##############################################
  callbackUrl: http://localhost:8989/callback
  modifyUserAfterCallback: true # 用户资料变更之后回调开关
  addFriendAfterCallback: false # 添加好友之后回调开关
  addFriendBeforeCallback: false # 添加好友之前回调开关
  modifyFriendAfterCallback: false # 修改好友之后回调开关
  deleteFriendAfterCallback: false # 删除好友之后回调开关
  addFriendShipBlackAfterCallback: false #添加黑名单之后回调开关
  deleteFriendShipBlackAfterCallback: false #删除黑名单之后回调开关
  createGroupAfterCallback: false # 创建群聊之后回调开关
  modifyGroupAfterCallback: false # 修改群聊之后回调开关
  destroyGroupAfterCallback: false # 解散群聊之后回调开关
  deleteGroupMemberAfterCallback: false # 删除群成员之后回调
  addGroupMemberAfterCallback: false # 拉人入群之后回调
  addGroupMemberBeforeCallback: false # 拉人入群之前回调
  sendMessageAfterCallback: false # 发送单聊消息之后
  sendMessageBeforeCallback: false # 发送单聊消息之前
  sendGroupMessageAfterCallback: false # 发送群聊消息之后
  sendGroupMessageBeforeCallback: false # 发送群聊消息之前
  offlineMessageCount: 1000 #离线消息存储条数
  deleteConversationSyncMode: 1 #1多段同步


# 日志
#logging:
#  config: classpath:logback-spring.xml

# Mybatis-Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      update-strategy: not_empty
  type-aliases-package: com.dh.im.service.friendship.dao


httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true